# Generated by Django 3.1.1 on 2020-09-12 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_auto_20200911_1933'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_image',
            field=models.ImageField(blank=True, height_field=300, null=True, upload_to='', width_field=300),
        ),
    ]
