# Generated by Django 3.1.1 on 2020-09-12 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0007_auto_20200912_1008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likecount',
        ),
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
    ]
