# Generated by Django 3.1.1 on 2020-09-15 17:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0010_auto_20200915_0036'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='likeowner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='like_by_whom', to=settings.AUTH_USER_MODEL),
        ),
    ]
